### ISSUE TITLE
No portuguese (brazil)

### ISSUE THREAD

**Issue by Hyhbec** [sixtriangles/sixtriangles.github.io#10]
I'd like to help to translate it to my native language Portuguese (Brazil).

**Comment by sixtriangles** [comment]
Hello, thank you, this would be very helpful!
If you'd like to translate it, the files which need translating can be
found here:
https://github.com/sixtriangles/sixtriangles.github.io

Specifically, these files (csv files can be edited in a spreadsheet editor
such as excel or google sheets)
Triangles.csv - Needs 4 new columns, pt, pt0, pt1, and pt2, and translate
the word in each column with the word
languages.csv - Needs 1 new column, pt, and translate each line. The $ is
replaced by the words in pt0, pt1, and pt2 from the previous file.
Unfortunately, I don't have a good way to allow these to change based on
word gender. My Portuguese isn't great, but if it can be followed by
multiple gendered words and has a different form, you could try something
like "um(a)". Perhaps not quite as clean as the English version, and I'm
open to suggestions, but I think that would be easiest.
questions.csv - the biggest file probably, needs an it column with all the
sentences translated
index.html - you can edit this in a text editor, everything from like line
31-77 probably should be translated so people know what their scores mean.
Don't touch the html stuff inside the <>. (you'll see lots of 'p' and 'h3'
and 'strong', those don't need any sort of translating)

Thanks so much for your time! If you have any further questions, please
feel free to reply :)

**Comment by sixtriangles** [comment]
Closing this as there's been no reply for a while, if there's interest in translating it to this, a new issue can be opened.
