### ISSUE TITLE
I'd like to add Korean.

### ISSUE THREAD

**Issue by tnghks1245** [sixtriangles/sixtriangles.github.io#16]
I'd like to help to translate it to my native language Korean.

[sixtriangles.github.io-master_ko.zip](https://github.com/sixtriangles/sixtriangles.github.io/files/5218284/sixtriangles.github.io-master_ko.zip)

Please let me know what needs to be added and improved to the translated file.

**Comment by sixtriangles** [comment]
Hello, thank you, this would be very helpful!
I'll take a look at the file sometime this week and try to merge it in.

**Comment by tnghks1245** [comment]
> 안녕하세요, 감사합니다. 매우 도움이 될 것입니다!
> 이번 주에 파일을 살펴보고 병합 해 보겠습니다.

If there is a better translation later on, the article will be posted. I will work on it first and leave a better translation for other Koreans.
이후에 더 좋은 번역이 있다면 글이 올라올 것입니다. 제가 먼저 작업을 해서 다른 한국인이 더 좋은 번역문을 남길 것입니다.

**Comment by tnghks1245** [comment]
> 안녕하세요, 감사합니다. 매우 도움이 될 것입니다!
> 이번 주에 파일을 살펴보고 병합 해 보겠습니다.

Thank You! 
감사합니다!

**Comment by sixtriangles** [comment]
Apologies for the delay, but I've merged it in now, and I'll push the update to the website in a little bit
