### ISSUE TITLE
Polish translations - corrections

### ISSUE THREAD

**Issue by JarekMazurek** [sixtriangles/sixtriangles.github.io#18]
Current translation -> Corrected translation

Question X of Y: -> Pytanie X z Y:
Mocno się zgadzam -> Zdecydowanie się zgadzam
Nie zgadzam -> Nie zgadzam się
Mocno się nie zgadzam -> Zdecydowanie się nie zgadzam
Poprzedni -> Poprzednie

**Comment by sixtriangles** [comment]
All of these except the question have been updated and the website will be updated soon.
I've realized the question isn't translated to any language, so that will take a bit more work to fix...
