### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Jakkub122** [sixtriangles/sixtriangles.github.io#2]
I can help to translate it

**Comment by sixtriangles** [comment]
Hi! Polish would help a lot. All the files are here: https://github.com/sixtriangles/sixtriangles.github.io
The ones which need to be translated:
index.html - starting at line 40, going down to 84. Ignore the HTML tags, just translate the text.
Name the Polish version pl.html

And the following csv files can be opened in a spreadsheet editor such as excel, google drive, etc. Each needs new column(s) added. Add one titled pl (and pl0, pl1, pl2 for Triangles)
Files which need new columns:
Triangles.csv
Questions.csv
Languages.csv - note for this one, where there is a $, that is replaced with the words from Triangles.csv, to allow languages where those words come before or after. (i.e. if it's like English where you say "Extreme Imperialist", you'd do "Extreme $", whereas like Spanish I believe would be "$ Extremo" (I don't speak Spanish, that's fake Spanish for the sake of example). If words are gendered in Polish, you can use parentheses or slashes to indicate that it can be either, like (s)he, or ein(e).

After translating these, you can open a pull request and I can merge them in and run testing and link them up correctly to the other language pages, or you can email the files to me if that's easier.

Thank you so much for offering to help!

**Comment by sixtriangles** [comment]
I've received an email from someone else volunteering to translate it to Polish. Is there an easy way to split this, or would you prefer to do it all? I'm also open to other ideas.

**Comment by Jakkub122** [comment]
I don’t know person who also want to translate it to Polish but I think we could split it into half - I’d translate index.html, pl.html file and triangles.csv and we could split into half questions, but unfortunately I don’t know who is also working on it

**Comment by sixtriangles** [comment]
I've asked him to add a comment here. Also, just to clarify, index.html becomes pl.html, in case that wasn't clear.

**Comment by Jakkub122** [comment]
Yes, I almost finished it

**Comment by Jakkub122** [comment]
Now it's fully translated and finished
