### ISSUE TITLE
Errors in Russian version

### ISSUE THREAD

**Issue by sikamora** [sixtriangles/sixtriangles.github.io#6]
**This sentences is incorrect in Russian:**
Я не стал жить в стране, где все зарабатвают одинакого
Госдуарство необходимо для ликвидации монополий и гарантии честной конкуренции
Всё, чем может запралять свободный рынок, должно принадлежать ему
Рынок всегда будет производить лучшую продукцию, если в их дела не будет вмешиваться государство
Государство должно следить за всеми граждан для борьбы с терроризмом
Государство никогда не должно быть вправе наказывать людей за правду, даже на кону стоит национальная безопасность
Чиновники, которые умышленно обманвают народ, должны сидеть в тюрьме
СМИ должны больше стараться на тем, чтобы высказывать факты, чем мнения
Меня нация должна завоёвывать другие нации
Мир был бы лучше, если все страны дипломатическим путём объединились в единое мировое правительство
Мы должны заботиться об иностранных гражданах так же, как и своих собственных
Мы должны свергнуть все режимы, которые ущимляют права человека
Будь у меня возможность, я бы предтворил свою идеологию в жизнь, даже если большинство людей будет против
Правительство не должно терпимо относится к мнению десидентов
Народ должен подтвергать сомнению действия своих властителей
Малнькие правительства обычно лучше больших правительств
Доходы людей должны прямо зависить от ценности ими произвоидимой продукции
Дети богатых людей надо должны становится богатыми, только если у них есть своя собственная независимая бизнес-идея
Правительство должно помогать самым низким слоям общества
Важно предосталять бесплатное образование всем детям
**Right version:**
Я бы не стал жить в стране, где все зарабатывают одинаково
Государство необходимо для ликвидации монополий и гарантии честной конкуренции
Всё, чем может управлять свободный рынок, должно принадлежать ему
Рынок всегда будет производить лучшую продукцию, если в его дела не будет вмешиваться государство
Государство должно следить за всеми гражданами для борьбы с терроризмом
Государство никогда не должно быть вправе наказывать людей за правду, даже если на кону стоит национальная безопасность
Чиновники, которые умышленно обманывают народ, должны сидеть в тюрьме
СМИ должны больше стараться над тем, чтобы высказывать факты, чем мнения
Моя нация должна завоёвывать другие нации
Мир был бы лучше, если бы все страны дипломатическим путём объединились в единое мировое правительство
Мы должны заботиться об иностранных гражданах так же, как и о своих собственных
Мы должны свергнуть все режимы, которые ущемляют права человека
Будь у меня возможность, я бы претворил свою идеологию в жизнь, даже если большинство людей будет против
Правительство не должно терпимо относится к мнению диссидентов
Народ должен подвергать сомнению действия своих властителей
Маленькие правительства обычно лучше больших правительств
Доходы людей должны прямо зависеть от ценности ими производимой продукции
Дети богатых людей должны становится богатыми, только если у них есть своя собственная независимая бизнес-идея
Правительство должно помогать самым низшим слоям общества
Важно предоставлять бесплатное образование всем детям

**Comment by sixtriangles** [comment]
Hi, thanks for mentioning this! I believe I've fixed these now.

**Comment by sikamora** [comment]
Good work!
But you forgot to change the word "Госдуарство". Russian language doesn't have this word. "Государство" is right version.
